import { GlobalAlert } from "@/components/Alert";
import { AlertProvider } from "@/hooks/use-alert";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AlertProvider>
          <GlobalAlert />
          {children}
        </AlertProvider>
      </body>
    </html>
  );
}
