import HomeFooter from "@/views/home/home-footer";
import HomeTopNav from "@/views/home/home-top-nav";

import type { Metadata } from "next";
import "../globals.css";

import { AlertProvider } from "@/hooks/use-alert";
import { Inter } from "@next/font/google";

const inter = Inter({
  subsets: ["latin"], // Define o conjunto de caracteres
  weight: "400", // Peso padrão (Regular)
});

export const metadata: Metadata = {
  title: "Icarus",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={`${inter.className} !bg-white`}>
        <AlertProvider>
          <main
            style={{
              backgroundImage: "url('/background.webp')",
              backgroundAttachment: "fixed",
            }}
          >
            {/* Top nav */}
            <HomeTopNav />
            {children}
            {/* footer */}
            <HomeFooter />
          </main>
        </AlertProvider>
      </body>
    </html>
  );
}
